name: Release DLL on tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: |
          dotnet restore "Emby.Notifications.Discord.csproj"
          dotnet build "Emby.Notifications.Discord.csproj" -c Release --no-restore
      - name: Gather artifacts
        shell: bash
        run: |
          mkdir -p out
          find . -path "*/bin/Release/*" -name "*.dll" -print -exec cp {} ./out/ \;
          if [ -f "plugin.json" ]; then cp plugin.json ./out/; fi
          (cd out && zip -r ../Emby.Notifications.Discord_${{ github.ref_name }}.zip .)
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Emby.Notifications.Discord_${{ github.ref_name }}.zip
